---
homebridge_config_directory: /opt/configs

telegraf_plugins_extra:
  - name: docker
    options:
      endpoint: unix:///var/run/docker.sock
      timeout: 5s
      perdevice: "true"
      total: "true"
  - name: docker_log
    options:
      endpoint: unix:///var/run/docker.sock
      timeout: 5s
      source_tag: "true"

docker_compose_projects:
  - project_name: homebriddge
    pull: true
    definition:
      version: "3.4"

      services:
        homebridge:
          container_name: homebridge
          hostname: homebridge
          image: homebridge/homebridge:latest
          restart: unless-stopped
          network_mode: host
          privileged: true
          volumes:
            - /opt/homebridge:/homebridge
            - /var/run/dbus:/var/run/dbus:z
            - /etc/localtime:/etc/localtime:ro
          environment:
            PUID: "0"
            GUID: "0"
            TZ: America/Denver
            TERMINATE_ON_ERROR: "0"
            HOMEBRIDGE_INSECURE: "1"
            HOMEBRIDGE_DEBUG: "1"
            HOMEBRIDGE_CONFIG_UI: "1"
            HOMEBRIDGE_CONFIG_UI_PORT: "8081"
            HOMEBRIDGE_INIT_PORT: "51002"
#
#  goveev2:
#    image: oznu/homebridge:2021-12-02-debian-no-avahi
#    description: Ultimate Govee HomeKit Integration
#    restart_policy: unless-stopped
#    recreate: "{{ docker_recreate|default(false) }}"
#    pull: yes
#    privilaged: yes
#    network_mode: host
#    volumes:
#      - '{{ homebridge_config_directory }}/ultimate-govee:/homebridge'
#      - /etc/localtime:/etc/localtime:ro
#    env:
#      PUID: '0'
#      GUID: '0'
#      TZ: America/Denver
#      TERMINATE_ON_ERROR: '0'
#      HOMEBRIDGE_INSECURE: '1'
#      HOMEBRIDGE_DEBUG: '1'
#      HOMEBRIDGE_CONFIG_UI: '1'
#      HOMEBRIDGE_CONFIG_UI_PORT: '8082'
#      HOMEBRIDGE_INIT_PORT: '51003'
