---
- name: Deploy common server configurations
  hosts: all
  remote_user: root
  gather_facts: true

  vars_files:
    - vault.yml

  tasks:
    - name: Add common role
      ansible.builtin.import_role:
        name: common
