---
- name: Wait for SSM connection
  hosts: cts
  gather_facts: true

  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Install common packages
      ansible.builtin.package:
        name:
          - curl
          - vim
          - wget
          - python3
          - python3-dev
          - python3-pip
          - awscli
        state: present

    - name: Install pip dependencies
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        state: present

    - name: Setup docker
      ansible.builtin.include_role:
        name: docker
        tasks_from: install.yml
        vars_from: Ubuntu22.yml
      tags:
        - docker-install

    - name: Retrieve AWS ECR login password
      ansible.builtin.command:
        cmd: aws ecr get-login-password --region={{ aws_region }}
      register: ecr_token

    - name: Docker login to the ECR repository
      community.docker.docker_login:
        registry_url: "{{ ecr_repository }}"
        username: AWS
        password: "{{ ecr_token.stdout }}"
        reauthorize: true

    - name: Setup docker
      ansible.builtin.import_role:
        name: docker
