---
- name: Add ansible_play_hosts to /etc/hosts file
  hosts: excelero
  become: true
  tasks:
    - name: Add ansible_play_hosts to /etc/hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line:
          "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}
          {{ hostvars[item].ansible_fqdn }}"
        regexp: "^{{ hostvars[item].ansible_default_ipv4.address }}.*"
      with_items: "{{ ansible_play_hosts }}"
