---
- name: "Add hosts to Foreman server and start build process"
  hosts: all
  remote_user: root
  vars_files:
    - vault.yml

  tasks:
    - name: Add ilo role
      ansible.builtin.import_role:
        name: ilo
      when:
        - survey_provider is defined
        - survey_provider == "ilo"
