---
- name: Configure Rsyslog server/client
  hosts:
    - all
  remote_user: root
  gather_facts: true

  vars_files:
    - vault.yml

  tasks:
    - name: Add rsyslog role
      ansible.builtin.import_role:
        name: rsyslog
      tags:
        - rsyslog
