- name: Deploy Serial-Over-LAN configs
  hosts: all
  become: true
  remote_user: root
  tasks:
    - name: Add common role
      ansible.builtin.include_role:
        name: common
        tasks_from: redhat-sol
      when: ansible_os_family == "RedHat"
    - name: Add common role
      ansible.builtin.include_role:
        name: common
        tasks_from: ubuntu-sol
      when: ansible_os_family == "Debian"
