---
# Deploy Plex Media Server; NZB Services (Sonarr, Radarr, SABnzbd, OMBI);
# Apache webserver (vhosts + reverse proxy configs for media services); Samba and Apple File Protocol file sharing services
# Optionally deploy with NFS or CephFS storage backends (requires openldap role)

- name: Deploy nginx webservers
  hosts:
    - nginx
  remote_user: root
  gather_facts: true
  vars_files:
    - vault.yml
  tasks:
    - ansible.builtin.import_role:
        name: common
      tags:
        - common
    - ansible.builtin.import_role:
        name: openldap
      when: openldap_server_ip is defined and openldap_server_ip != None
      tags:
        - openldap
    - ansible.builtin.import_role:
        name: ceph-fs
      when:
        - shared_storage
        - storage_backend == "cephfs"
      tags:
        - cephfs
    - name: Add nginx role
      ansible.builtin.import_role:
        name: nginx
      when: "'webservices' in group_names"
      tags:
        - nginx
    - name: Add telegraf role
      ansible.builtin.import_role:
        name: telegraf
      when: "'telegraf' in group_names"
      tags:
        - telegraf
    - name: Run setup
      ansible.builtin.setup:
      tags:
        - always
