---
docker_install_community_edition: true
docker_install_nvidia: true
docker_nvidia_gpu_ids: "0"
docker_nvidia_gpu_caps: all

media_user_gid: 2000
media_user_uid: 2000
media_disk_mnt: /media
queued_dir: "{{ data_mount_root }}/queued"
transcoding_dir: "{{ data_mount_root }}/transcoding"
complete_dir: "{{ data_mount_root }}/complete"
incomplete_dir: "{{ data_mount_root }}/incomplete"
logs_dir: "{{ data_mount_root }}/logs"

tdarr:
  server:
    image: haveagitgat/tdarr:latest
    tdarr_port: 8266
    web_ui_port: 8265
  node:
    image: haveagitgat/tdarr_node:latest
    tdarr_port: 8267

docker_compose_projects:
  - project_name: tdarr_node
    pull: "{{ docker_recreate | default(False) }}"
    build: "{{ docker_recreate | default(False) }}"
    nocache: "{{ docker_recreate | default(False) }}"
    recreate: "{{ docker_recreate | default(False) }}"
    remove_orphans: "{{ docker_recreate | default(False) }}"
    definition:
      version: "3.9"
      x-logging: &default-logging
        driver: journald
      services:
        tdarr-node:
          hostname: tdarr-node
          container_name: tdarr_node
          image: "{{ tdarr.node.image }}"
          restart: unless-stopped
          volumes:
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
            - /opt/tdarr/server:/app/server
            - /opt/tdarr/config:/app/configs
            - "{{ transcoding_dir }}:/temp"
            - "{{ complete_dir }}:/complete"
            - "{{ queued_dir }}:/queued"
            - "{{ data_mount_root }}/tv:/tv"
            - "{{ data_mount_root }}/movies:/movies"
          devices:
            - /dev/dri/card0:/dev/dri/card0
            - /dev/dri/renderD128:/dev/dri/renderD128
          privileged: true
          network_mode: host
          environment:
            PUID: "{{ media_user_uid }}"
            PGID: "{{ media_user_gid }}"
            nodeID: "{{ ansible_host }}"
            nodeIP: "{{ ansible_default_ipv4.address }}"
            nodePort: "{{ tdarr.node.tdarr_port }}"
            serverIP: "{{ hostvars['tdarr-server']['ansible_host'] }}"
            serverPort: "{{ tdarr.server.tdarr_port }}"
            TZ: "{{ timezone }}"
            NVIDIA_DRIVER_CAPABILITIES: "{{ docker_nvidia_gpu_caps }}"
            NVIDIA_VISIBLE_DEVICES: "{{ docker_nvidia_gpu_ids }}"
          runtime: nvidia
          logging:
            <<: *default-logging
            options:
              tag: tdarr_node

telegraf_plugins_extra:
  - name: docker
    options:
      endpoint: unix:///var/run/docker.sock
      timeout: 5s
      perdevice: "true"
      total: "true"
  - name: docker_log
    options:
      endpoint: unix:///var/run/docker.sock
      timeout: 5s
      source_tag: "true"
  - name: nvidia_smi
